# Section 1 - Base Image
FROM python:3.10.2

# Section 2 - Python Interpreter Flags
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Section 3 - Compiler and OS libraries
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential netcat \
    && rm -rf /var/lib/apt/lists/*

# Section 4 - Project libraries and User Creation
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt \
    && rm -rf /tmp/requirements.txt \
    && useradd -U pnt

# Section 5 - Code and User Setup
WORKDIR /app
RUN mkdir  logs
RUN chmod 777 -R logs
RUN chmod +w -R logs
CMD ["chmod", "777 -R", "logs"]
USER pnt
COPY --chown=pnt:pnt . /app/

# Section 6 - Docker Run Checks and Configurations
CMD ["python", "-m","unittest", "-v"]